### ISSUE TITLE
Resources to build roms

### ISSUE THREAD

**Issue by willam011** [andrew264/android_device_lenovo_TB3710F#1]
I have forked the cm 12.1 repository for tb3_710f and am trying to build lineage os 15.1 (android Oreo go edition). Can you please help me with finding the device tree, device vendor files and the kernel which you have and are using for development on this device.

**Comment by willam011** [comment]
I found two device trees one by dev andrew264 and other by szazs89 attached here.
Please tell which to use for building los 15.1 (Oreo go)

**Comment by andrew264** [comment]
My trees for TB3-710F are fine for cm-14.1. You need to modify it to get
oreo working.

**Comment by willam011** [comment]
I was wondering whether a single device tree could be used for any version of android. Is it not correct? If it's not please explain me what kind of changes are to be made as I am not much of a dev myself.

**Comment by andrew264** [comment]
Update android binder to O in the kernel tree.
Update shim libs to keep the old blobs working.
Port old patches to work with new branches.

**Comment by willam011** [comment]
Can I use the attached xml as a local manifest for the rom building

**Comment by willam011** [comment]
Can I use the attached xml file as a local manifest for this device
https://raw.githubusercontent.com/szazs89/device_lenovo_TB3_710F/master/roomservice.xml

**Comment by willam011** [comment]
> Update android binder to O in the kernel tree. Update shim libs to keep the old blobs working. Port old patches to work with new branches.

Sorry dev but I don't know what you are saying. Can you please help me understand the process and provide some resources for learning about these and other stuff.

**Comment by androdev2** [comment]
Hey @willam011 can you not use lenovo open source code for the build which can be found here[](https://github.com/andrewsanthosh/Andy-lite-wifi-OSC)

**Comment by androdev2** [comment]
Hey @willam011 , can you not use Lenovo open source code available [here](https://github.com/andrewsanthosh/Andy-lite-wifi-OSC) for the build

**Comment by andrew264** [comment]
> Can I use the attached xml file as a local manifest for this device
> [szazs89/device_lenovo_TB3_710F@`master`/roomservice.xml (raw)](https://raw.githubusercontent.com/szazs89/device_lenovo_TB3_710F/master/roomservice.xml)

if you are building cm-14.1
device tree: https://github.com/andrew264/android_device_lenovo_TB3710F
kernel: https://github.com/andrew264/android_kernel_lenovo_mt8127
vendor tree: https://github.com/andrew264/android_vendor_lenovo_TB3710F

just apply the patches from device tree no other repositories are required.

**Comment by willam011** [comment]
> > Can I use the attached xml file as a local manifest for this device
> > [szazs89/device_lenovo_TB3_710F@`master`/roomservice.xml (raw)](https://raw.githubusercontent.com/szazs89/device_lenovo_TB3_710F/master/roomservice.xml)
> 
> if you are building cm-14.1
> device tree: https://github.com/andrew264/android_device_lenovo_TB3710F
> kernel: https://github.com/andrew264/android_kernel_lenovo_mt8127
> vendor tree: https://github.com/andrew264/android_vendor_lenovo_TB3710F
> 
> just apply the patches from device tree no other repositories are required.

Thanks for your help but I am trying to build los 15.1.
